CREATE TABLE IF NOT EXISTS musica (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(150) NOT NULL,
    artista VARCHAR(150) NOT NULL,
    album VARCHAR(150) NOT NULL,
    genero VARCHAR(80) NOT NULL,
    duracao VARCHAR(5) NOT NULL,
    ano_lancamento INT NOT NULL
);

INSERT INTO musica
(titulo, artista, album, genero, duracao, ano_lancamento)
VALUES
('Blinding Lights', 'The Weeknd', 'After Hours', 'Pop', '03:20', 2020);

INSERT INTO musica
(titulo, artista, album, genero, duracao, ano_lancamento)
VALUES
('Billie Jean', 'Michael Jackson', 'Thriller', 'Pop', '04:54', 1982);
